import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from "/components/Hero";
import Footer from "/components/Footer";
import {IoMdPlay} from "react-icons/io";
import {MdPause} from "react-icons/md";
import React from 'react';
import Menu from "/components/Menu";
import Header from '../../components/Header';
function Projects({menu}) {


  



  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header theme="light"/>

      <Menu/>
     

   


     
     

     


      <Footer/>

      
    </div>
  )
}


const mapStateToProps = state => ({
    menu:state.appReducer.menu
  })
export default connect(mapStateToProps,null)(Projects);