import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Hero from "/components/Hero";
import Footer from "/components/Footer";
import {IoMdPlay} from "react-icons/io";
import {MdPause} from "react-icons/md";
import React from 'react';
import Menu from "/components/Menu";
import Header from '../../components/Header';
import { connect } from 'react-redux';
import Project from '../../components/Project';
function Projects({menu,setMenu}) {
  React.useEffect(()=>{
    setMenu(false)
},[])

  



  return (
    <div className={styles.project}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header theme="light" position={'fixed'}/>

      <Project product_image={'/assets/project-1.png'}/>
      <Project product_image={'/assets/project-2.png'}/>
      <Project product_image={'/assets/project-3.png'}/>
      <Project product_image={'/assets/project-4.png'}/>

      <Menu/>
     

   


     
     

     


      <Footer/>

      
    </div>
  )
}


const mapStateToProps = state => ({
    menu:state.appReducer.menu
  })

  const mapDispatchToProps = dispatch => ({
    setMenu: (menu) => dispatch({ type: 'SET_MENU', menu })
})
export default connect(mapStateToProps,mapDispatchToProps)(Projects);