import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from "/components/Hero";
import Menu from "/components/Menu";
import {IoMdPlay} from "react-icons/io";
import {MdPause} from "react-icons/md";
import React from 'react';
import Footer from "/components/Footer";
import { connect } from 'react-redux';
function Home({menu,setMenu}) {


  
  React.useEffect(()=>{
    setMenu(false)
},[])




  const [played,setPlayed] = React.useState(false);
  const [video_played,setVideoPlayed] = React.useState(false);



    

  const handlePlay = ()=>{
      const video = document.querySelector('.video_hero');
      video.play();
      setPlayed(true);
  }
  const handlePause = ()=>{
      const video = document.querySelector('.video_hero');
      
      video.pause();
      
      setPlayed(false);
      
  }


  const handlePlayVideo = ()=>{
      const video = document.querySelector('.video_section');
      video.play();
      setVideoPlayed(true);
  }

  const handlePauseVideo = ()=>{
    const video = document.querySelector('.video_section');
    video.pause();
    setVideoPlayed(false);
  }




  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      <section className='bg-white  px-16  lg:px-0 py-16 lg:py-32 relative'>
        <div className="section-static lg:flex items-start gap-16">
          <div className="section-static-image ">
            <img src="/assets/red_jacket.png" alt="red_jacket"/>
          </div>
          <div className="section-static-content mt-8">
    <h4 className='w-full lg:w-[350px]'>Special Photography Studio Based in Berlin, Germany</h4>
    <p className='w-full lg:w-[370px]'>Always taking great pleasure in the work we do, we find satisfaction in the simple acts of thinking and making. Since 2005, we’ve worked to build strategies and craft solutions for our collaborators, applying reason and rationality to the process of design.</p>
    <button className=' flex w-32 mt-5 justify-between items-center'>About us <img src="/assets/arrow.svg" alt="" /></button>
          </div>
        </div>
        <div className="mt-5 section-absolute static lg:absolute right-10 bottom-10">
          <img src="/assets/black_white.png" alt="black_white" />
        </div>
      </section>

      <section className=" section-2 text-white bg-black py-16 px-8 sm:px-16 lg:px-32 flex lg:flex-row flex-col justify-between gap-32">
        <div className="section-content flex flex-col gap-12  items-start lg:items-end ">
          <p className="text-2xl section-count w-full flex justify-end items-start">
            03
          </p>
          <div className={`${styles.section_content_main} flex justify-end items-start lg:items-end flex-col`}>
            <p className='w-full text-left lg:text-right'>Featured Project</p>
            <h4 className='w-full lg:w-[350px] text-left lg:text-right'>Project Title</h4>
            <p className='w-full lg:w-[370px] text-left lg:text-right'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <button className=' flex  gap-8 mt-5 justify-between items-center'>View project <img src="/assets/arrow_white.svg" alt="" /></button>
          </div>
        </div>
        <div className="section-image">
          <img src="/assets/girl-in-white.png" alt="" />
        </div>
      </section>


      <section className={`${styles.video_section} relative  h-[60vh] sm:h-[70vh] lg:h-[100vh] bg-white`}>

        <video src="/assets/video_hero.mp4"  className='absolute w-full  h-full object-cover video_hero' loop onClick={!played?handlePlay:handlePause}></video>

        <div className="video-section-content text-white absolute top-[-5px] lg:top-10 left-[5px] sm:left-10  translate-x-1 translate-y-12 lg:translate-x-1/2 lg:translate-y-1/2">
          <p className="section-counter">02</p>
          <p>Featured Project</p>
          <h4 className='w-full lg:w-[350px]'>Project Title</h4>
          <p className='w-full sm:w-[350px] lg:w-[370px]'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <button className=' flex  gap-8 mt-5 justify-between items-center'>View project <img src="/assets/arrow_white.svg" alt="" /></button>
        </div>
        <div className={`${styles.video_controls}`}>
        <button className="play-pause-btn px-3 py-3 bg-white rounded-full" onClick={!played?handlePlay:handlePause}>
                       {!played? <IoMdPlay/>:<MdPause/>}
                    </button>
        </div>
      </section>

      <section className=" bg-white section-2 text-black bg-white py-16 px-8 sm:px-16 lg:px-32 flex lg:flex-row flex-col justify-between gap-32">
        <div className="section-content flex flex-col gap-12  items-start lg:items-end ">
          <p className="text-2xl section-count w-full flex justify-end items-start">
            04
          </p>
          <div className={`${styles.section_content_main} flex justify-end items-start lg:items-end flex-col`}>
            <p className='w-full text-left lg:text-right'>Featured Project</p>
            <h4 className='text-left lg:text-right'>Project Title</h4>
            <p className='text-left lg:text-right w-full lg:w-[370px]'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <button className=' flex  gap-8 mt-5 justify-between items-center'>View project <img src="/assets/arrow.svg" alt="" /></button>
          </div>
        </div>
        <div className="section-image">
          <img src="/assets/black_jacket.png" alt="" />
        </div>
      </section>

      <section className=' bg-white lg:px-32 flex flex-col lg:flex-row justify-between'>
        <div className="section-left-content flex flex-col">
        <p className="text-2xl section-count w-full flex lg:justify-start items-start">
            04
          </p>
        <p className='w-full text-left'>Featured Project</p>
        <div className={`relative ${styles.section_video} mt-3 w-full lg:w-[370px]`}>
          {/* <img src="/assets/ordinary.png" alt="" className='w-full'/> */}
          <video src="/assets/production.mp4" loop className='w-full h-full object-cover video_section'></video>
          <div className={`${styles.video_controls_second}`}>
        <button className="play-pause-btn flex items-center justify-center w-16 backdrop-blur-md bg-white/60 h-16 bg-white rounded-full" onClick={!video_played?handlePlayVideo:handlePauseVideo}>
                       {!video_played? <IoMdPlay/>:<MdPause/>}
                    </button>
        </div>
        </div>
        <div className="mt-5">
        <h4>Ordinary Challenge</h4>
        <p className='w-full lg:w-[370px]'>Oridnary is a Gothenburg-based creative development studio. Through technology and design they differentiate artists, creatives and brands to help them break through the noise. Oridnary likes to challenge the ordinary.</p>
        <button className='flex  gap-8 mt-5 justify-between items-center'>View project <img src="/assets/arrow.svg" alt="" /></button>
        </div>
        </div>

        <div className="section-right-content mt-12 lg:mt-0 w-full lg:w-auto">
          <img src="/assets/ethnic.png" alt="" className='w-full lg:w-auto'/>
        </div>
      </section>



 <Menu/>
      <Footer/>

      
    </div>
  )
}

const mapStateToProps = state => ({
  menu:state.appReducer.menu
})

const mapDispatchToProps = dispatch => ({
  setMenu: (menu) => dispatch({ type: 'SET_MENU', menu })
})
export default connect(mapStateToProps,mapDispatchToProps)(Home);